release 4.1.1

diff --git a/bin/operations b/bin/operations
--- a/bin/operations
+++ b/bin/operations
@@ -616,8 +616,9 @@ function get-artifact-base-name()
 }
 
 #
-# returns the artifact file name, as it will be generated by Maven, including base name, optionally version and
-# extension. It's either 'finalName' + extension (if exists) or 'artifactId' + version + extension.
+# returns the artifact file name (not the path), as it will be generated by Maven, including base name, optionally
+# version and extension. It's either 'finalName' + extension (if exists) or 'artifactId' + version + extension.
+# If built, the artifact file name is typically located under ${project_home}/target
 #
 function get-artifact-file-name()
 {
@@ -1159,41 +1160,51 @@ function do-release() {
         info "got --no-push, we don't push to the remote repository"
     fi
 
-    #
-    # If we release externally (as a zip file), we only need to create the JAR locally in the project, so we package.
-    # If we release to LOCAL_MAVEN, we install
-    #
-
+    local release_binary_artifact
     local maven_testing_configuration=""
     ! ${run_tests_option} &&  maven_testing_configuration="-Dmaven.test.skip=true"
 
     if is-local-maven-release; then
         mvn ${maven_testing_configuration} clean install || \
             fail "failed to pass tests, must restore the version in pom.xml to ${current_version} manually"
+
+        release_binary_artifact=${project_home}/target/$(get-artifact-file-name)
+        [ -f ${release_binary_artifact} ] || \
+            fail "release binary artifact ${release_binary_artifact} not found, something went wrong with the maven build process"
+
     else
         mvn ${maven_testing_configuration} clean package || \
             fail "failed to pass tests, must restore the version in pom.xml to ${current_version} manually"
-        local release_zip_file_path
-        release_zip_file_path=$(build-release-zip-file) || exit 1
-        install-release ${release_zip_file_path}
+        release_binary_artifact=$(build-release-zip-file) || exit 1
+        install-release ${release_binary_artifact}
     fi
+
+    #
+    # increment locally to the next patch snapshot
+    #
+    current_version=$(get-version)
+    local next_local_version
+    next_local_version=$(compute-next-version "${current_version}" patch) || exit 1
+    next_local_version=$(compute-next-version "${next_local_version}" snapshot) || exit 1
+    debug "next local version ${next_local_version}"
+
+    yes "setting next local version ${next_local_version}, is this OK?" || return 0;
+    set-version ${next_local_version}
 
     local msg="A new ${mode} version (${next_version}) was released"
 
     if ${tagged}; then
-
         msg="${msg}, committed to repository and tagged."
     else
         msg="${msg} and committed to repository."
     fi
 
     info ""
+    info "RELEASE SUMMARY:"
+    info ""
     info ${msg}
-    info "If you want to create an official GitHub release, use tag \"${tag}\" and the following binary: ${release_zip_file_path}"
-    info ""
-
-    info ""
-    info "TODO: ask whether to start a new major/minor/patch snapshot, and start it ..."
+    info "If you want to create an official GitHub release, use tag \"${tag}\" and the binary ${release_binary_artifact}"
+    info "The local version has been incremented to ${next_local_version}"
     info ""
 }
 
