release 4.1.2-SNAPSHOT-2

diff --git a/bin/operations b/bin/operations
--- a/bin/operations
+++ b/bin/operations
@@ -268,7 +268,7 @@ function get-project-name() {
 }
 
 #
-# returns the project version as specified in the pom.xml file
+# Returns the project version as specified in the pom.xml file, at stdout
 #
 function get-version() {
 
@@ -287,7 +287,10 @@ function get-version() {
 }
 
 #
-# replaces the version string in pom.xml with the version given as argument
+# Replaces the version string in pom.xml with the version given as argument, if they are different.
+# There are cases when set version is a noop, for example when releasing the current snapshot: the
+# POM file already contains the correct version, and subsequent functions will increment it to the
+# appropriate post-release "current" version.
 #
 function set-version() {
 
@@ -300,8 +303,16 @@ function set-version() {
     [ -z "${pom_file}" ] && pom_file=${project_home}/pom.xml
     [ -f ${pom_file} ] || fail "pom.xml file ${pom_file} not found"
 
+    local current_version
+    current_version=$(get-version) || fail "failed to get the current version from pom.xm"
+
+    if [ "${version}" = "${current_version}" ]; then
+        debug "the provided version ${version} and the current pom.xml version are identical"
+        return 0
+    fi
+
     #
-    # replace the first occurrence of <version>...</version> with our version
+    # if different, replace the first occurrence of <version>...</version> with our version
     #
 
     debug "inserting version ${version}"
@@ -319,8 +330,8 @@ function set-version() {
 # gets the current version as declared in POM and computes the version for the release
 # being processed. 'mode' can be "major", "minor", "patch", "snapshot" or a full version
 # string. If a full version string is provided, the function will verify that is a valid
-# version string and the version it # specifies if newer than the current version.
-# Sends the version string at stdout.
+# version string and the version it specifies if newer than the current version. Sends
+# the version string at stdout.
 #
 function compute-release-version() {
 
@@ -389,7 +400,14 @@ function compute-release-version() {
         fi
         snapshot=""
     elif [ "${mode}" = "snapshot" ]; then
-        if [ -z "${snapshot}" ]; then
+        if [ -n "${snapshot}" ]; then
+            #
+            # the current version is a snapshot, releasing a snapshot means releasing
+            # the current snapshot we were working on and incrementing the snapshot
+            # number.
+            #
+            debug "the current snapshot ${snapshot} is being released"
+        else
             #
             # current release is a dot release, increment to the next patch snapshot 1
             #
@@ -402,11 +420,6 @@ function compute-release-version() {
             else
                 patch=$(expr ${patch} + 1) || exit 1
             fi
-        else
-            #
-            # regular snapshot
-            #
-            snapshot=$(expr ${snapshot} + 1) || exit 1
         fi
     else
         local new_version=${mode}
@@ -1123,6 +1136,7 @@ function do-release() {
 
     local release_version
     release_version=$(compute-release-version "${current_version}" "${mode}") || exit 1
+
     debug "release version ${release_version}"
 
     yes "releasing ${release_version}, is this OK?" || { info "release canceled, no files were changed"; return 0; }
@@ -1191,6 +1205,8 @@ function do-release() {
     local next_local_version
     next_local_version=$(compute-next-version "${current_version}" snapshot) || exit 1
     debug "next local version ${next_local_version}"
+
+    exit 255
 
     yes "setting next local version ${next_local_version}, is this OK?" || return 0;
     set-version ${next_local_version}
