upgraded operations

diff --git a/bin/operations b/bin/operations
--- a/bin/operations
+++ b/bin/operations
@@ -26,13 +26,24 @@ Commands:
 
     install [-f|--force]
 
-    release <snapshot|minor|major|patch|"version-string">
+    release <info|snapshot|minor|major|patch|"version-string">
 
-        Makes a release by incrementing the release information appropriately, running all tests, building the final
-        artifact and installing the artifact in the appropriate repository. If a version string is used, the string
-        is checked for consistency. The release process will fail if the version string is invalid or represents an
-        older version than the current version. The repository can be the local Maven repository, a directory, a
-        remote server, etc.
+        If 'info' is used, returns the current version information.
+
+        Makes a release by incrementing the release information appropriately, running all tests,
+        tagging the repository, building the final artifact and installing the artifact in the
+        appropriate artifact repository.
+
+        If 'snapshot' is used, and the current release is a dot release, it will be incremented to
+        the next patch snapshot release. If the current release is a snapshot release, the
+        snapshot counter will be simply incremented.
+
+        If a version string is used, the string is checked for consistency. The release process
+        will fail if the version string is invalid or represents an older version than the current
+        version. The repository can be the local Maven repository, a directory, a remote server,
+        etc.
+
+        Also see https://kb.novaordis.com/index.php/Public_Release_Procedure_for_Projects
 
      test - internal release tools testing shortcut. Advanced users only.
 
@@ -40,10 +51,11 @@ Installation:
 
     ./src/main/bash/operations install-release-tools <project-home-directory>
 
-        The installation functionality can currently only be accessed from the original repository.
-        'install-release-tools' installs the release tools into the 'bin' subdirectory of the specified project home
-        directory. A target directory qualifies as "project home directory" if it has a Maven pom.xml in it. If an
-        older version of the release tools is already installed, 'install-release-tools' will upgrade in place.
+        The installation functionality can currently only be accessed from the original
+        repository. 'install-release-tools' installs the release tools into the 'bin' subdirectory
+        of the specified project home directory. A target directory qualifies as "project home
+        directory" if it has a Maven pom.xml in it. If an older version of the release tools is
+        already installed, 'install-release-tools' will upgrade in place.
 
 Per-Project Configuration:
 
@@ -159,6 +171,16 @@ function info
 {
     echo "$@" 1>&2;
     return 0
+}
+
+#
+# Asks the question and it expects a y/n answer. If the answer starts with 'y', returns 0, otherwise it returns 1
+#
+function yes
+{
+    echo -n "$@ [y/n] " 1>&2;
+    read line
+    [ "${line:0:1}" = "y" ] && return 0 || return 1
 }
 
 #
@@ -291,21 +313,68 @@ function compute-next-version() {
     debug "major=${major}, minor=${minor}, patch=${patch}, snapshot=${snapshot}"
 
     if [ "${mode}" = "major" ]; then
-        major=$(expr ${major} + 1) || exit 1
+        #
+        # only increment if we're not a snapshot
+        #
+        if [ -z "${snapshot}" ]; then
+            major=$(expr ${major} + 1) || exit 1
+        fi
         minor=""
         patch=""
         snapshot=""
     elif [ "${mode}" = "minor" ]; then
-        minor=$(expr ${minor} + 1) || exit 1
+
+        [ -z "${minor}" ] && minor=0
+        if [ -n "${snapshot}" ]; then
+            #
+            # we're a snapshot
+            #
+            if [ -n "${patch}" ]; then
+                #
+                # we're a patch snapshot, so increment the minor
+                #
+                minor=$(expr ${minor} + 1) || exit 1
+            else
+                debug "we're a minor snapshot, we don't increment the minor"
+                #
+                # we're a minor snaps
+                #
+            fi
+        else
+            #
+            # we're not a snapshot
+            #
+            minor=$(expr ${minor} + 1) || exit 1
+        fi
         patch=""
         snapshot=""
     elif [ "${mode}" = "patch" ]; then
-        patch=$(expr ${patch} + 1) || exit 1
+        [ -z "${patch}" ] && patch=0
+        #
+        # if we're snapshot, keep the patch level
+        #
+        if [ -z "${snapshot}" ]; then
+            patch=$(expr ${patch} + 1) || exit 1
+        fi
         snapshot=""
     elif [ "${mode}" = "snapshot" ]; then
         if [ -z "${snapshot}" ]; then
+            #
+            # current release is a dot release, increment to the next patch snapshot 1
+            #
             snapshot=1
+            if [ -z "${patch}" ]; then
+                patch=1
+                if [ -z "${minor}" ]; then
+                    minor=0
+                fi
+            else
+                patch=$(expr ${patch} + 1) || exit 1
+            fi
         else
+            #
+            # regular snapshot
+            #
             snapshot=$(expr ${snapshot} + 1) || exit 1
         fi
     else
@@ -590,7 +659,7 @@ function configure-run-wrapper()
         fi
     done
 
-    [ -z "${run_wrapper_file}" ] && fail "no run wrapper file found in ${zip_bin_dir}"
+    [ -z "${run_wrapper_file}" ] && fail "no run wrapper file found in ${zip_bin_dir} (or none of the following files: [$(ls ${zip_bin_dir})] contains a main=class= line ...)"
 
     debug "run wrapper file: ${run_wrapper_file}"
 
@@ -790,14 +859,16 @@ function install-release() {
 
     debug-arguments "$@"
 
-    [ -z "${release_repository}" ] && \
-        fail "'release_repository' not defined. Check your local configuration file ${configuration_file}"
-
-    debug "release repository: ${release_repository}"
-
     local release_file_path=$1
     [ -z "${release_file_path}" ] && fail "'release_file' not provided"
     [ -f ${release_file_path} ] || fail "the release file ${release_file_path} does not exist"
+
+    debug "release repository: ${release_repository}"
+
+    if [ -z "${release_repository}" ]; then
+        info "no 'release_repository' defined in ${configuration_file}, the binary release available as ${release_file_path} ..."
+        return 0
+    fi
 
     local target_file=${release_repository}/$(basename ${release_file_path})
 
@@ -811,8 +882,12 @@ function install-release() {
 # return 0 if the configured release_repository is LOCAL_MAVEN
 function is-local-maven-release() {
 
-    [ -z "${release_repository}" ] && \
-        fail "'release_repository' not defined. Check your local configuration file ${configuration_file}"
+    if [ -z "${release_repository}" ]; then
+        #
+        # no ${release_repository} defined, that means we'll handle the binary artifact manually
+        #
+        return 1
+    fi
 
     [ "${release_repository}" = "LOCAL_MAVEN" ] && return 0 || return 1
 }
@@ -947,7 +1022,7 @@ function do-install() {
     debug "checking whether the project installation zip has been built ..."
 
     local release_zip_file_path
-    release_zip_file_path=$(build-relese-zip-file) || exit 1
+    release_zip_file_path=$(build-release-zip-file) || exit 1
 
     local installed_path
     installed_path=$(install ${release_zip_file_path} ${RUNTIME_DIR} ${force}) || exit 1
@@ -980,17 +1055,45 @@ function do-release() {
     # checking pre-requisites
     #
 
-    [ -z "${mode}" ] && fail "snapshot|minor|major|patch or the version string must be specified"
+    [ -z "${mode}" ] && fail "info|snapshot|minor|major|patch or the version string must be specified"
 
     local current_version
     current_version=$(get-version) || exit 1
     debug "current version: ${current_version}"
 
+    if [ "${mode}" = "info" ]; then
+        # report the current version and exit
+        info "current version: ${current_version}"
+        return 0
+    fi
+
     local next_version
     next_version=$(compute-next-version "${current_version}" "${mode}") || exit 1
     debug "next version ${next_version}"
 
+    yes "releasing ${next_version}, is this OK?" || { info "release canceled, no files were changed"; return 0; }
+
     set-version ${next_version}
+
+    #
+    # run the tests with the new version
+    #
+
+    mvn clean test || fail "test suite failed after version increment, manual intervention required"
+
+    #
+    # tag repository
+    #
+
+    git add . && info "git add ok" || fail "git add . failed"
+
+    git commit -m "release ${next_version}" && info "git commit ok" || fail "git commit failed"
+
+    local tag=release-${next_version}
+
+    git tag -m "release ${next_version}" "${tag}" && info "git tag ok, tagged with ${tag}" || fail "git tag failed"
+
+    git push --follow-tags && info "git push ok" || fail "git push failed"
 
     #
     # If we release externally (as a zip file), we only need to create the JAR locally in the project, so we package.
@@ -1007,13 +1110,13 @@ function do-release() {
     fi
 
     info ""
-    info "###########################################################################################"
-    info "#"
-    info "#    A new ${mode} version (${next_version}) was released locally, you may want to commit and push git #"
-    info "#"
-    info "###########################################################################################"
+    info "A new ${mode} version (${next_version}) was released, committed to repository and tagged."
+    info "If you want to create an official GitHub release, use tag \"${tag}\" and the following binary: ${release_zip_file_path}"
     info ""
 
+    info ""
+    info "TODO: ask whether to start a new major/minor/patch snapshot, and start it ..."
+    info ""
 }
 
 main $@
